info:
  name: Settings
  type: http
  seq: 2

http:
  method: GET
  url: "{{AWTRIX_WEB_URL}}/api/settings"
  auth:
    type: basic
    username: "{{AWTRIX_USER}}"
    password: "{{AWTRIX_PASSWORD}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
